CREATE external TABLE
IF NOT EXISTS mfc_behavior.email_account_log_history (
	action string,
	actionDetail string,
	actionStatus string,
	actionTime string,
	actionType string,
	apkSource string,
	appVer BIGINT,
	bizDate string,
	clientIp string,
	clientRegion string,
	clientType string,
	device string,
	did string,
	email string,
	LANGUAGE string,
	loginType string,
	plan string,
	ts BIGINT,
	uid string,
	vendorId string,
	LocalCreateTimestamps BIGINT,
	CountryCode string,
	CityName string,
	AutonomousSystemOrganization string,
	AutonomousSystemNumber BIGINT,
	GeoHash string,
	StateCode string,
	Location map <string,float>
) ROW format serde 'org.openx.data.jsonserde.JsonSerDe' stored AS textfile Location '/mfc/user_log/email_account_log_history';

CREATE external TABLE
IF NOT EXISTS mfc_behavior.email_account_log (
	localForwardIp string,
	action string,
	actionDetail string,
	actionStatus string,
	actionTime bigint,
	actionType string,
	apkSource string,
	appVer BIGINT,
	bizDate string,
	clientIp string,
	clientRegion string,
	clientType string,
	device string,
	did string,
	email string,
	LANGUAGE string,
	loginType string,
	plan string,
	ts BIGINT,
	uid string,
	vendorId string,
	LocalCreateTimestamps BIGINT,
	CountryCode string,
	CityName string,
	AutonomousSystemOrganization string,
	AutonomousSystemNumber BIGINT,
	GeoHash string,
	StateCode string,
	Location map <string,float>
) ROW format serde 'org.openx.data.jsonserde.JsonSerDe' stored AS textfile Location '/mfc/user_log/email_account_log';

insert into table email_account_log select "",action,actionDetail,actionStatus,1000*unix_timestamp(actionTime,"yyyy-MM-dd'T'HH:mm:ss.SSSXXX"),
	actionType,apkSource,appVer,bizDate,clientIp,clientRegion,clientType,device,did,email,LANGUAGE,loginType,plan,ts,uid,vendorId,LocalCreateTimestamps,CountryCode,CityName,
	AutonomousSystemOrganization,AutonomousSystemNumber,GeoHash,StateCode,Location from email_account_log_history;